name: Sync from Template

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    
    # ➕➕➕ 重点：必需添加这部分权限设置 ➕➕➕
    permissions:
      contents: write       # 允许写入代码 (git push)
      pull-requests: write  # 允许创建 PR
    # ➕➕➕ 结束 ➕➕➕

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: sansan0/TrendRadar
          upstream_branch: main
          pr_labels: sync_template
          # 确保这里引用了 token
          github_token: ${{ secrets.GITHUB_TOKEN }}
